// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: ShortenerService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // упрощённо: передаём userID напрямую
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortRequest) Reset() {
	*x = CreateShortRequest{}
	mi := &file_ShortenerService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortRequest) ProtoMessage() {}

func (x *CreateShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortRequest.ProtoReflect.Descriptor instead.
func (*CreateShortRequest) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShortRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateShortResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	// conflict = true, если URL уже был (аналог 409)
	Conflict      bool `protobuf:"varint,2,opt,name=conflict,proto3" json:"conflict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortResponse) Reset() {
	*x = CreateShortResponse{}
	mi := &file_ShortenerService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortResponse) ProtoMessage() {}

func (x *CreateShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortResponse.ProtoReflect.Descriptor instead.
func (*CreateShortResponse) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortResponse) GetConflict() bool {
	if x != nil {
		return x.Conflict
	}
	return false
}

type ResolveShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShortRequest) Reset() {
	*x = ResolveShortRequest{}
	mi := &file_ShortenerService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShortRequest) ProtoMessage() {}

func (x *ResolveShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShortRequest.ProtoReflect.Descriptor instead.
func (*ResolveShortRequest) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveShortRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResolveShortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"` // false => аналог 410/404
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveShortResponse) Reset() {
	*x = ResolveShortResponse{}
	mi := &file_ShortenerService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveShortResponse) ProtoMessage() {}

func (x *ResolveShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveShortResponse.ProtoReflect.Descriptor instead.
func (*ResolveShortResponse) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveShortResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ResolveShortResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchItem) Reset() {
	*x = BatchItem{}
	mi := &file_ShortenerService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchItem) ProtoMessage() {}

func (x *BatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchItem.ProtoReflect.Descriptor instead.
func (*BatchItem) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{4}
}

func (x *BatchItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BatchItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortBatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortBatchResult) Reset() {
	*x = ShortBatchResult{}
	mi := &file_ShortenerService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortBatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortBatchResult) ProtoMessage() {}

func (x *ShortBatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortBatchResult.ProtoReflect.Descriptor instead.
func (*ShortBatchResult) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{5}
}

func (x *ShortBatchResult) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortBatchResult) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type CreateShortBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*BatchItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortBatchRequest) Reset() {
	*x = CreateShortBatchRequest{}
	mi := &file_ShortenerService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortBatchRequest) ProtoMessage() {}

func (x *CreateShortBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateShortBatchRequest) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{6}
}

func (x *CreateShortBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShortBatchRequest) GetItems() []*BatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateShortBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ShortBatchResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortBatchResponse) Reset() {
	*x = CreateShortBatchResponse{}
	mi := &file_ShortenerService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortBatchResponse) ProtoMessage() {}

func (x *CreateShortBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateShortBatchResponse) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{7}
}

func (x *CreateShortBatchResponse) GetResults() []*ShortBatchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_ShortenerService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{8}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_ShortenerService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ShortenerService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_ShortenerService_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_ShortenerService_proto protoreflect.FileDescriptor

const file_ShortenerService_proto_rawDesc = "" +
	"\n" +
	"\x16ShortenerService.proto\x12\fshortener.v1\"?\n" +
	"\x12CreateShortRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"N\n" +
	"\x13CreateShortResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12\x1a\n" +
	"\bconflict\x18\x02 \x01(\bR\bconflict\"%\n" +
	"\x13ResolveShortRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x14ResolveShortResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"U\n" +
	"\tBatchItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"V\n" +
	"\x10ShortBatchResult\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"a\n" +
	"\x17CreateShortBatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.shortener.v1.BatchItemR\x05items\"T\n" +
	"\x18CreateShortBatchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.shortener.v1.ShortBatchResultR\aresults\"\x0e\n" +
	"\fStatsRequest\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\xdb\x02\n" +
	"\tShortener\x12R\n" +
	"\vCreateShort\x12 .shortener.v1.CreateShortRequest\x1a!.shortener.v1.CreateShortResponse\x12U\n" +
	"\fResolveShort\x12!.shortener.v1.ResolveShortRequest\x1a\".shortener.v1.ResolveShortResponse\x12a\n" +
	"\x10CreateShortBatch\x12%.shortener.v1.CreateShortBatchRequest\x1a&.shortener.v1.CreateShortBatchResponse\x12@\n" +
	"\x05Stats\x12\x1a.shortener.v1.StatsRequest\x1a\x1b.shortener.v1.StatsResponseB8Z6github.com/divanov-web/shorturl/internal/grpcserver/pbb\x06proto3"

var (
	file_ShortenerService_proto_rawDescOnce sync.Once
	file_ShortenerService_proto_rawDescData []byte
)

func file_ShortenerService_proto_rawDescGZIP() []byte {
	file_ShortenerService_proto_rawDescOnce.Do(func() {
		file_ShortenerService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ShortenerService_proto_rawDesc), len(file_ShortenerService_proto_rawDesc)))
	})
	return file_ShortenerService_proto_rawDescData
}

var file_ShortenerService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ShortenerService_proto_goTypes = []any{
	(*CreateShortRequest)(nil),       // 0: shortener.v1.CreateShortRequest
	(*CreateShortResponse)(nil),      // 1: shortener.v1.CreateShortResponse
	(*ResolveShortRequest)(nil),      // 2: shortener.v1.ResolveShortRequest
	(*ResolveShortResponse)(nil),     // 3: shortener.v1.ResolveShortResponse
	(*BatchItem)(nil),                // 4: shortener.v1.BatchItem
	(*ShortBatchResult)(nil),         // 5: shortener.v1.ShortBatchResult
	(*CreateShortBatchRequest)(nil),  // 6: shortener.v1.CreateShortBatchRequest
	(*CreateShortBatchResponse)(nil), // 7: shortener.v1.CreateShortBatchResponse
	(*StatsRequest)(nil),             // 8: shortener.v1.StatsRequest
	(*StatsResponse)(nil),            // 9: shortener.v1.StatsResponse
}
var file_ShortenerService_proto_depIdxs = []int32{
	4, // 0: shortener.v1.CreateShortBatchRequest.items:type_name -> shortener.v1.BatchItem
	5, // 1: shortener.v1.CreateShortBatchResponse.results:type_name -> shortener.v1.ShortBatchResult
	0, // 2: shortener.v1.Shortener.CreateShort:input_type -> shortener.v1.CreateShortRequest
	2, // 3: shortener.v1.Shortener.ResolveShort:input_type -> shortener.v1.ResolveShortRequest
	6, // 4: shortener.v1.Shortener.CreateShortBatch:input_type -> shortener.v1.CreateShortBatchRequest
	8, // 5: shortener.v1.Shortener.Stats:input_type -> shortener.v1.StatsRequest
	1, // 6: shortener.v1.Shortener.CreateShort:output_type -> shortener.v1.CreateShortResponse
	3, // 7: shortener.v1.Shortener.ResolveShort:output_type -> shortener.v1.ResolveShortResponse
	7, // 8: shortener.v1.Shortener.CreateShortBatch:output_type -> shortener.v1.CreateShortBatchResponse
	9, // 9: shortener.v1.Shortener.Stats:output_type -> shortener.v1.StatsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ShortenerService_proto_init() }
func file_ShortenerService_proto_init() {
	if File_ShortenerService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ShortenerService_proto_rawDesc), len(file_ShortenerService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ShortenerService_proto_goTypes,
		DependencyIndexes: file_ShortenerService_proto_depIdxs,
		MessageInfos:      file_ShortenerService_proto_msgTypes,
	}.Build()
	File_ShortenerService_proto = out.File
	file_ShortenerService_proto_goTypes = nil
	file_ShortenerService_proto_depIdxs = nil
}
